name: Test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        php: ["8.0", "8.1"]
    env:
      tools: composer, phpstan
      ini-values: default_charset='UTF-8'
      key: cache-1652276840262
    name: PHP ${{ matrix.php }} test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: ${{ env.ini-values }}
          coverage: pcov
          tools: ${{ env.tools }}
        env:
          fail-fast: true
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Validate composer
        run: composer validate
      - name: Get composer cache directory
        if: ${{ !env.ACT }}
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --classmap-authoritative --ignore-platform-reqs
      - name: Run PHPStan
        run: phpstan analyse src -l 9
      - name: Tests (PHPUnit)
        run: vendor/bin/phpunit --coverage-xml=build/logs/xml-coverage --log-junit=build/logs/junit.xml
      # - name: Mutation testing (Infection)
      #   env:
      #     INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
      #   run: |
      #     curl -sLOJ https://github.com/infection/infection/releases/download/0.26.13/infection.phar
      #     curl -sLOJ https://github.com/infection/infection/releases/download/0.26.13/infection.phar.asc
      #     gpg --recv-keys C6D76C329EBADE2FB9C458CFC5095986493B4AA0
      #     gpg --with-fingerprint --verify infection.phar.asc infection.phar
      #     chmod +x infection.phar
      #     ./infection.phar --coverage=build/logs --min-covered-msi=90 --threads=$(nproc) --logger-github --only-covered
